cask_args appdir: '/Applications'

# devtools
brew 'awscli'
brew 'awslogs'
brew 'bat'
brew 'ctags'
brew 'fd'
brew 'fzf'
brew 'gifsicle'
brew 'git'
brew 'imagemagick'
brew 'jq'
brew 'lazygit'
brew 'neovim'
brew 'nnn'
brew 'nodejs'
brew 'postgresql@16'
brew 'python3'
brew 'ripgrep'
brew 'tig'
brew 'wget'
brew 'yarn'
brew 'ykman'

# apps
cask 'acorn'
cask 'firefox'
tap 'homebrew/cask-fonts'
cask 'font-symbols-only-nerd-font'
cask 'gitup'
cask 'google-chrome'
cask 'hammerspoon'
cask 'iterm2'
cask 'kaleidoscope'
cask 'launchbar'
cask 'slack'
cask 'sublime-text'
