#!/bin/zsh

setup() {
  SETUPDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
}

install_omz() {
  echo "Installing Oh My Zsh...\n"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

install_nvim_config() {
  echo "Installing Neovim config...\n"
  mkdir -p "$HOME/.config"

  if [ -d "$HOME/.config/nvim" ]; then
    echo '!!! ~/.config/nvim already exists !!!\n'
  else
    pushd "$HOME/.config"
      git clone https://github.com/tomas-nava/neovim-lazyvim-config nvim
    popd
  fi
}

link_dotfiles() {
  echo "Linking dotfiles...\n"
  # custom scripts directory
  if [ ! -d "$HOME/bin" ]; then
    ln -sf "$SETUPDIR/bin $HOME/bin"
  else
    echo '!!! ~/bin already exists !!!\n'
  fi

  # move the default .zshrc if omz added it
  if [ -f "$HOME/.zshrc" ] && [ ! -L "$HOME/.zshrc" ]; then
    echo "!!! Renaming existing .zshrc to .zshrc.omz-installed !!!\n"
    mv "$HOME/.zshrc" "$HOME/.zshrc.omz-installed"
  fi
  # so we can symlink our own
  ln -sf "$SETUPDIR/.zshrc" "$HOME/.zshrc"

  # custom terminal prompt theme
  ln -sf "$SETUPDIR/tagnoster.zsh-theme" "$HOME/.oh-my-zsh/themes/tagnoster.zsh-theme"

  # git
  cp -f "$SETUPDIR/.gitconfig" "$HOME/.gitconfig"

  # hammerspoon
  mkdir -p "$HOME/.hammerspoon"
  ln -sf "$SETUPDIR/init.lua" "$HOME/.hammerspoon/init.lua"
}

main() {
  setup

  echo "Installing applications with homebrew...\n"
  brew update
  brew bundle
  brew link git --force

  install_omz
  install_nvim_config
  link_dotfiles
}

main $@
