#!/bin/zsh

setup() {
  SETUPDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
}

install_omz() {
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

link_dotfiles() {
  ln -s "$SETUPDIR/bin $HOME/bin"
  ln -s "$SETUPDIR/.zshrc" "$HOME/.zshrc"
  ln -s "$SETUPDIR/tagnoster.zsh-theme" "$HOME/.oh-my-zsh/themes/tagnoster.zsh-theme"
  cp "$SETUPDIR/.gitconfig" "$HOME/.gitconfig"
  mkdir -p "$HOME/.hammerspoon"
  ln -s "$SETUPDIR/init.lua" "$HOME/.hammerspoon/init.lua"
}

install_nvim_config() {
  echo "Installing neovim config\n"
  mkdir -p "$HOME/.config"
  pushd "$HOME/.config"
    git clone https://github.com/tomas-nava/neovim-lazyvim-config nvim
  popd
}

main() {
  setup

  brew update
  brew bundle
  brew link git --force

  install_powerline
  install_omz
  install_nvim_config
  link_dotfiles
}

main $@
